version: "3.9"
services:
  postgresql:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=CALENDAR
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - app
networks:
  app:
